//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artwork_Sharing_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id_Comment { get; set; }
        public string Content_Co { get; set; }
        public Nullable<System.DateTime> Date_Sub { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<int> Id_ArtworkP { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User_Platform User_Platform { get; set; }
    }
}
