//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artwork_Sharing_Platform.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Artwork_SharingEntities : DbContext
    {
        public Artwork_SharingEntities()
            : base("name=Artwork_SharingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillOrder> BillOrders { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Follow> Follows { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Interact> Interacts { get; set; }
        public virtual DbSet<MoMo> MoMoes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Participation> Participations { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Permission_Detail> Permission_Detail { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<RateStar> RateStars { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportDetail> ReportDetails { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Reward> Rewards { get; set; }
        public virtual DbSet<User_Platform> User_Platform { get; set; }
        public virtual DbSet<UserReward> UserRewards { get; set; }
    }
}
