//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artwork_Sharing_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoMo
    {
        public int Id_MoMo { get; set; }
        public string Phone_MoMo { get; set; }
        public string Name_MoMo { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
