//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artwork_Sharing_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id_OrderDetail { get; set; }
        public Nullable<System.DateTime> Date_Order { get; set; }
        public Nullable<int> Id_BillOrder { get; set; }
        public Nullable<double> Price_Order { get; set; }
        public Nullable<int> Id_ArtworkP { get; set; }
        public Nullable<int> Quanity { get; set; }
    
        public virtual BillOrder BillOrder { get; set; }
        public virtual Post Post { get; set; }
    }
}
