//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artwork_Sharing_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission_Detail
    {
        public int Id_PerDetail { get; set; }
        public Nullable<int> Role { get; set; }
        public string Action_Name { get; set; }
        public string Action_Code { get; set; }
        public Nullable<bool> Check_Action { get; set; }
    
        public virtual Permission Permission { get; set; }
    }
}
