//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artwork_Sharing_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Platform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Platform()
        {
            this.BillOrders = new HashSet<BillOrder>();
            this.Comments = new HashSet<Comment>();
            this.Follows = new HashSet<Follow>();
            this.Interacts = new HashSet<Interact>();
            this.Notifications = new HashSet<Notification>();
            this.Participations = new HashSet<Participation>();
            this.Posts = new HashSet<Post>();
            this.Reports = new HashSet<Report>();
            this.Requests = new HashSet<Request>();
            this.UserRewards = new HashSet<UserReward>();
        }
    
        public int Id_User { get; set; }
        public string FullName_User { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string CCCD { get; set; }
        public string Address_User { get; set; }
        public string Phone_User { get; set; }
        public Nullable<System.DateTime> Date_UserRe { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role { get; set; }
        public string Picture_User { get; set; }
        public string Email { get; set; }
        public Nullable<int> Id_Rate { get; set; }
        public Nullable<bool> User_Premium { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOrder> BillOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interact> Interacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participation> Participations { get; set; }
        public virtual Permission Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        public virtual RateStar RateStar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserReward> UserRewards { get; set; }
    }
}
