//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artwork_Sharing_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReward
    {
        public int Id_UserReward { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<int> Id_Reward { get; set; }
        public Nullable<System.DateTime> Date_UserReward { get; set; }
    
        public virtual Reward Reward { get; set; }
        public virtual User_Platform User_Platform { get; set; }
    }
}
